ticker_id_dict = {
    'ADA': 0,
    'APT': 1,
    'ARB': 2,
    'ATOM': 3,
    'BCH': 4,
    'BNB': 5,
    'BTC': 6,
    'DOT': 7,
    'ETC': 8,
    'ETH': 9,
    'FIL': 10,
    'INJ': 11,
    'LINK': 12,
    'LTC': 13,
    'MATIC': 14,
    'MKR': 15,
    'SOL': 16,
    'UNI': 17,
    'XRP': 18,
    'AVAX': 19,
}

id_ticker_dict = {
    0: 'ADA',
    1: 'APT',
    2: 'ARB',
    3: 'ATOM',
    4: 'BCH',
    5: 'BNB',
    6: 'BTC',
    7: 'DOT',
    8: 'ETC',
    9: 'ETH',
    10: 'FIL',
    11: 'INJ',
    12: 'LINK',
    13: 'LTC',
    14: 'MATIC',
    15: 'MKR',
    16: 'SOL',
    17: 'UNI',
    18: 'XRP',
    19: 'AVAX'
}
